# Site Settings
name: JACOB
title: Software Engineering
description: This is a blog created to share my engineering experience.
tags:
  - react
  - typescript
  - aws
  - redux
  - mobx
  - mst
  - styled-components
  - graphql
  - gatsby
  - nextjs
  - apollo
  - apollo-client
  - esnext
  - es6+
  - es7
  - es8
email: hwangwonjun@gmail.com
disqus_username: hwangtan
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Feed
    url: /feed.xml